CREATE TABLE ABC (
    CODIGO INTEGER NOT NULL PRIMARY KEY,
    DESCRICAO CHAR(1)
);

INSERT INTO ABC (CODIGO, DESCRICAO) VALUES (1, 'A');
INSERT INTO ABC (CODIGO, DESCRICAO) VALUES (2, 'B');
INSERT INTO ABC (CODIGO, DESCRICAO) VALUES (3, 'C');

COMMIT;
